services:
  webapp:
    build:
      context: .
      dockerfile: Webapp/Dockerfile
    container_name: purchase-requests-app
#    pull_policy: always
#    restart: unless-stopped
    expose:
      - 8080
    ports:
      - "80:8080"
    environment:
        - MONGODB_URL=mongodb://10.5.0.12:27017
    volumes:
      - C:/Users/aelmendo/Documents/PR_Volume/Files:/purchase_requests
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    depends_on:
      - filestorage
    networks:
      station_net:
        ipv4_address: 10.5.0.11
  mongodb:
    image: mongo:latest
    container_name: mongodb
    pull_policy: always
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - C:/Users/aelmendo/Documents/PR_Volume/db:/data/db
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    networks:
      station_net:
        ipv4_address: 10.5.0.12

networks:
  station_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1

